version: '3.2'

services:
  dcm:
    build:
        context: .
        dockerfile: ./etc/dev/node/Dockerfile
    command:
      - "npm"
      - "start"
    ports:
      - "9991:9991"

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass123!
      - MYSQL_DATABASE=dcm
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: